[versions]
kotlin = "1.8.20"
ksp = "1.8.20-1.0.11"
kotlinpoet = "1.13.0"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
rgxgen = { module = "com.github.curious-odd-man:rgxgen", version = "1.4" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet"  }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "4.1.0" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.24.2" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }